### ISSUE TITLE
SUGGESTION:  Show what element caused the kick on console

### ISSUE THREAD

**Issue by Mrgaton** [DiffuseHyperion/InertiaAntiCheat#27] opened 2024-03-22 17:27 UTC
i am having trouble making this to work so this feature would be nice to me and probably to anyone new that want this to work quickly

**Comment by Mrgaton** [comment] 2024-03-22 17:31
![image](https://github.com/DiffuseHyperion/InertiaAntiCheat/assets/68958481/7ecaafac-8a9f-4712-a2af-e611d844e2c7)
umm what i am doing wrong?

```toml
# Immediately kick players who do not have these mods in their modlist.
# Enabling debug will show the full modlist of players joining, allowing you to discover mod names.

whitelist = ["Applied Energistics 2"," AppleSkin"," Aquamirae"," Auto HUD"," BCLib"," Better End"," Better Nether"," Camera Overhaul"," Cardinal Components API (base)"," Cardinal Components API (entities)"," Chat Heads"," cloth-basic-math"," Cloth Config v11"," core"," toml"," mclib"," toml4j"," Comforts"," Croptopia"," Distant Horizons"," Dynamic Crosshair"," Eating Animation"," EpheroLib"," Fabric API"," Fabric API Base"," Fabric API Lookup API (v1)"," Fabric Biome API (v1)"," Fabric Block API (v1)"," Fabric BlockView API (v2)"," Fabric BlockRenderLayer Registration (v1)"," Fabric Client Tags"," Fabric Command API (v1)"," Fabric Command API (v2)"," Fabric Commands (v0)"," Fabric Containers (v0)"," Fabric Content Registries (v0)"," Fabric Convention Tags"," Fabric Crash Report Info (v1)"," Fabric Data Attachment API (v1)"," Fabric Data Generation API (v1)"," Fabric Dimensions API (v1)"," Fabric Entity Events (v1)"," Fabric Events Interaction (v0)"," Fabric Events Lifecycle (v0)"," Fabric Game Rule API (v1)"," Fabric Item API (v1)"," Fabric Item Group API (v1)"," Fabric Key Binding API (v1)"," Fabric Key Bindings (v0)"," Fabric Lifecycle Events (v1)"," Fabric Loot API (v2)"," Fabric Loot Tables (v1)"," Fabric Message API (v1)"," Fabric Mining Level API (v1)"," Fabric Model Loading API (v1)"," Fabric Models (v0)"," Fabric Networking API (v1)"," Fabric Networking (v0)"," Fabric Object Builder API (v1)"," Fabric Particles (v1)"," fabric-permissions-api"," Fabric Recipe API (v1)"," Fabric Registry Sync (v0)"," Fabric Renderer API (v1)"," Fabric Renderer - Indigo"," Fabric Renderer Registries (v1)"," Fabric Rendering Data Attachment (v1)"," Fabric Rendering Fluids (v1)"," Fabric Rendering (v0)"," Fabric Rendering (v1)"," Fabric Resource Conditions API (v1)"," Fabric Resource Loader (v0)"," Fabric Screen API (v1)"," Fabric Screen Handler API (v1)"," Fabric Sound API (v1)"," Fabric Transfer API (v1)"," Fabric Transitive Access Wideners (v1)"," Fabric Loader"," FabricSkyBoxes"," Forge Config API Port"," GeckoLib 4"," Iceberg"," Immersive Aircraft"," Indium"," InertiaAntiCheat"," Inventory Sorter"," glsl-transformer"," Iris"," OpenJDK 64-Bit Server VM"," Kirin UI"," Kyrpt Config"," Legendary Tooltips"," Lithium"," Memory Leak Fix"," Minecraft"," MixinExtras"," Naturalist"," Obscure API"," jcpp"," antlr4-runtime"," MathParser.org-mXparser"," Presence Footsteps"," Prism"," 3d-Skin-Layers"," Sodium"," Sound Physics Remastered"," SpectreLib"," Starlight"," Energy"," Simple Voice Chat"," WunderLib"," YetAnotherConfigLibExtensions"]

```

**Comment by DiffuseHyperion** [comment] 2024-03-25 02:32
1. This doesn't look like an error message caused by this mod. Can you show the full kick message and console logs?
2. Try using modlists instead of a giant whitelist. See [here](https://github.com/DiffuseHyperion/InertiaAntiCheat/wiki/Legacy-(Version-0.0.6.2-and-under)#checking-against-a-hash)

**Comment by Mrgaton** [comment] 2024-03-25 08:39
I just copy pasted the mods that showed up on the console when the client loged in

**Comment by Mrgaton** [comment] 2024-03-25 08:40
Oh i see I think I putted a space in some nanes

**Comment by OmaigatTER** [comment] 2024-03-25 08:51
there is a way to disable the client having to hash all the mods? because it takes a bit to do

**Comment by OmaigatTER** [comment] 2024-03-25 08:58
it takes so much that the client gets kicked out from the grace time :c

**Comment by OmaigatTER** [comment] 2024-03-25 08:59
i even tried to put it to 10 seconds but it takes around 20 and I don't want to wait that much every time I join the server

**Comment by DiffuseHyperion** [comment] 2024-03-25 15:01
> Oh i see I think I putted a space in some nanes

Assuming this is resolved so closing this issue

> there is a way to disable the client having to hash all the mods? because it takes a bit to do

Weird that it's taking so long, since in the alpha versions the client doesn't hash anything, it just sends a list of all loaded mod names to the server. This should be nearly instantaneous, so not sure why its taking so long. Try enabling debug mode and see if its the client or server being slow, and open a new ticket :)

**Closed by DiffuseHyperion** 2024-03-25 15:01 UTC

**Comment by Mrgaton** [comment] 2024-03-25 18:06
On the console it shows the mod pack hahs

**Comment by Mrgaton** [comment] 2024-03-25 19:07
```
[20:06:40] [Netty Server IO #2/INFO]: [InertiaAntiCheat] literal{Mrgaton} is joining with the following modlist: [Applied Energistics 2, AppleSkin, Aquamirae, Auto HUD, BCLib, Better End, Better Nether, Camera Overhaul, Cardinal Components API (base), Cardinal Components API (entities), Chat Heads, cloth-basic-math, Cloth Config v11, core, toml, mclib, toml4j, Comforts, Croptopia, Distant Horizons, Dynamic Crosshair, Eating Animation, EpheroLib, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric Block API (v1), Fabric BlockView API (v2), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Attachment API (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Group API (v1), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Model Loading API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), fabric-permissions-api, Fabric Recipe API (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, FabricSkyBoxes, Forge Config API Port, GeckoLib 4, Iceberg, Immersive Aircraft, Indium, InertiaAntiCheat, Inventory Sorter, glsl-transformer, Iris, OpenJDK 64-Bit Server VM, Kirin UI, Kyrpt Config, Legendary Tooltips, Lithium, Memory Leak Fix, Minecraft, MixinExtras, Naturalist, Obscure API, jcpp, antlr4-runtime, MathParser.org-mXparser, Presence Footsteps, Prism, 3d-Skin-Layers, Sodium, Sound Physics Remastered, SpectreLib, Starlight, Energy, Simple Voice Chat, WunderLib, YetAnotherConfigLibExtensions]
[20:06:40] [Thread-27/INFO]: [InertiaAntiCheat] literal{Mrgaton}'s modlist hash: PpWbK+RrmAj6YKAQr3ZIXQ==
```

**Comment by Mrgaton** [comment] 2024-03-25 19:08
it says the modlist hash but that hash only the file names or the mod binary itself

**Comment by DiffuseHyperion** [comment] 2024-03-26 01:24
> it says the modlist hash but that hash only the file names or the mod binary itself

The hash of a list of file names
